jobs:
  - name: production job
    description: job that runs our production models
    environment_id: 68525
    settings:
      threads: 4
      target_name: prod
    triggers:
      github_webhook: False
      schedule: True
      custom_branch_only: False
    schedule:
      date:
        type: custom_cron
        cron: 0 1 * * *
    execute_steps:
      - dbt run
      - dbt test
    generate_docs: False
